In [56]:
import numpy as np

In [35]:
ab=[323,432,3,42,256,4,3]

In [37]:
ab

[323, 432, 3, 42, 256, 4, 3]

In [43]:
ab[2]==3

True

In [39]:
ba=np.array(ab)*2

In [41]:
ba

array([646, 864,   6,  84, 512,   8,   6])

In [44]:
np.max(ab)

np.int64(432)

In [45]:
np.min(ab)

np.int64(3)

In [4]:
a=np.array([11,2,2,1,342])
a

array([ 11,   2,   2,   1, 342])

In [8]:
b=np.array([[31,42,142,1,3],[24,234,1,3,1]])
b

array([[ 31,  42, 142,   1,   3],
       [ 24, 234,   1,   3,   1]])

In [10]:
b.shape

(2, 5)

In [14]:
np.linspace(1,10,10,dtype="int32")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.ones(10,dtype="int32").reshape(5,2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [20]:
np.identity(6,dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [25]:
i=np.identity(10,dtype="float").reshape(10,10)[1:][:5]

In [26]:
i.ndim


2

In [29]:
i.itemsize


8

In [30]:
a

array([ 11,   2,   2,   1, 342])

In [57]:
a.astype(np.float32)

array([ 11.,   2.,   2.,   1., 342.], dtype=float32)

In [50]:
a


array([ 11,   2,   2,   1, 342])

In [53]:
np.mean(a)
np.median(a)
np.std(a)

np.float64(135.24880775814623)

In [ ]:
np.size(a)

5

In [58]:
np.prod(a)

np.int64(15048)

In [59]:
np.amin(a)

np.int64(1)

In [60]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

In [68]:
cube[1,1:2,1:2]

array([[14]])

In [69]:
cube[1,1:2,:1]

array([[13]])

In [70]:
cube[0,2:,2:]

array([[9]])

In [71]:
cube[0,1:,1:]

array([[5, 6],
       [8, 9]])

In [72]:
cube[::-1]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [79]:
cube

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
cube[0]+cube[1]

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [75]:
np.argmax(cube)

np.int64(17)

In [80]:
np.argmin(cube)

np.int64(0)

In [81]:
np.cumsum(cube)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171])

In [83]:
np.histogram(cube,bins=[0,10,20,30,40,50,60])

(array([9, 9, 0, 0, 0, 0]), array([ 0, 10, 20, 30, 40, 50, 60]))

In [85]:
np.isin(cube,18)

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False,  True]]])

In [87]:
np.flip(cube)

array([[[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [88]:
a

array([ 11,   2,   2,   1, 342])

In [92]:
a=np.delete(a,0)

In [91]:
a

array([ 11,   2,   2,   1, 342])

In [93]:
a=np.reshape(a,(2,2))

In [94]:
a

array([[  2,   2],
       [  1, 342]])

In [102]:
np.random.rand()

0.7841381141878725

In [115]:
np.random.randint(8,10,size=(2,2))

array([[9, 8],
       [9, 8]], dtype=int32)

In [116]:
a[a>3]

array([342])

In [117]:
a

array([[  2,   2],
       [  1, 342]])

In [118]:
a=a.ravel()

In [119]:
a

array([  2,   2,   1, 342])

In [120]:
b

array([[ 31,  42, 142,   1,   3],
       [ 24, 234,   1,   3,   1]])

b=b[0:1,:4]

In [123]:
b=b[0:1,:4].ravel

In [125]:
b


<function ndarray.ravel(order='C')>

In [126]:
b=np.array([23,24,12,42])

In [129]:
np.vstack((a,b))

array([[  2,   2,   1, 342],
       [ 23,  24,  12,  42]])

In [135]:
c=np.concatenate((a,b),axis=0)

In [139]:
c

array([  2,   2,   1, 342,  23,  24,  12,  42])

In [134]:
np.hstack((a,a))

array([  2,   2,   1, 342,   2,   2,   1, 342])

In [140]:
np.split(c,8)

[array([2]),
 array([2]),
 array([1]),
 array([342]),
 array([23]),
 array([24]),
 array([12]),
 array([42])]

In [141]:
c

array([  2,   2,   1, 342,  23,  24,  12,  42])

In [149]:
mean=c.mean()

In [143]:
std=c.std()

In [156]:
t=4
outliers=c[np.abs(c-mean)>t*std]

In [157]:
outliers

array([], dtype=int64)

In [160]:
np.nunique(c)

AttributeError: module 'numpy' has no attribute 'nunique'

In [162]:
c

array([  2,   2,   1, 342,  23,  24,  12,  42])

In [166]:
np.sort(c)[::-1]

array([342,  42,  24,  23,  12,   2,   2,   1])