In [3]:
import numpy as np

In [4]:
a=np.random.randint(1,100,25)

In [5]:
a

array([71, 59, 37, 87, 98,  2, 76, 41, 73, 65, 92, 15, 55, 67, 18,  9, 77,
       72, 51, 17,  9, 62, 38,  3, 40], dtype=int32)

In [7]:
np.append(a,200)

array([ 71,  59,  37,  87,  98,   2,  76,  41,  73,  65,  92,  15,  55,
        67,  18,   9,  77,  72,  51,  17,   9,  62,  38,   3,  40, 200])

In [8]:
b=np.random.randint(1,100,24).reshape(6,4)

In [20]:
c=np.random.randint(1,50,20).reshape(5,4)
d=np.random.randint(1,30,16).reshape(4,4)

In [22]:
np.concatenate((c,d),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [23]:
np.where(a>50,0,a)

array([ 0,  0, 37,  0,  0,  2,  0, 41,  0,  0,  0, 15,  0,  0, 18,  9,  0,
        0,  0, 17,  9,  0, 38,  3, 40], dtype=int32)

In [27]:
np.where(a==70)

(array([], dtype=int64),)

In [29]:
np.argmax(a)
a

array([71, 59, 37, 87, 98,  2, 76, 41, 73, 65, 92, 15, 55, 67, 18,  9, 77,
       72, 51, 17,  9, 62, 38,  3, 40], dtype=int32)

In [31]:
np.argmax(b,axis=0)

array([1, 5, 5, 1])

In [32]:
b

array([[33, 61, 35,  6],
       [95,  5, 14, 94],
       [66, 10, 36, 38],
       [50, 49, 37, 60],
       [55, 19,  7, 36],
       [17, 88, 80,  6]], dtype=int32)

In [39]:

np.argmax(b,axis=0)

array([1, 5, 5, 1])

In [38]:
np.cumsum(b,axis=0)

array([[ 33,  61,  35,   6],
       [128,  66,  49, 100],
       [194,  76,  85, 138],
       [244, 125, 122, 198],
       [299, 144, 129, 234],
       [316, 232, 209, 240]])