In [2]:
import numpy as np

In [ ]:
# a=np.nan*np.empty(10)
# a[4]=1
# a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [12]:
a=int(input())
b=int(input())

c=np.random.random(a*b).reshape(a,b)
print(c)
np.average(c)

[[0.44731522 0.83601436 0.92136597 0.71750971 0.21754026]
 [0.42123734 0.36315516 0.7863573  0.33251163 0.69671309]]


np.float64(0.5739720036236737)

In [19]:
def borderArray(x,y):
    a=np.ones((x,y))
    a[1:-1,1:-1]=0
    print(a)

borderArray(4,5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.linspace(0,4,25).reshape(5,5)

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [25]:
a=np.zeros((5,5))
a+=np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])